version: '3.9'

services:
  auth_service:
    volumes:
      - ./services/auth_service:/app
      - ./shared:/app/shared
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  event_service:
    volumes:
      - ./services/event_service:/app
      - ./shared:/app/shared
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  user_service:
    volumes:
      - ./services/user_service:/app
      - ./shared:/app/shared
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  notification_service:
    volumes:
      - ./services/notification_service:/app
      - ./shared:/app/shared
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
